/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author srp5391
 */
public class EndScreen extends javax.swing.JFrame {

    /**
     * Creates new form EndScreen
     */
    public EndScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Min_Bat_Vol = new javax.swing.JLabel();
        Average_Power = new javax.swing.JLabel();
        kW_Hours = new javax.swing.JLabel();
        Max_Bat_Vol = new javax.swing.JLabel();
        Min_Av_Vol_Cell = new javax.swing.JLabel();
        Low_Cell = new javax.swing.JLabel();
        High_Cell = new javax.swing.JLabel();
        mBatVol = new javax.swing.JLabel();
        aVPower = new javax.swing.JLabel();
        kWHours = new javax.swing.JLabel();
        mXBatVol = new javax.swing.JLabel();
        mAVCell = new javax.swing.JLabel();
        lCell = new javax.swing.JLabel();
        hCell = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        aVLog = new javax.swing.JTextArea();
        Test_Completed = new javax.swing.JLabel();
        tComp = new javax.swing.JLabel();
        Total_Test_Duration = new javax.swing.JLabel();
        tDuration = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        Min_Bat_Vol.setText("Minimum Battery Voltage:");
        Min_Bat_Vol.setToolTipText("");

        Average_Power.setText("Average Power:");

        kW_Hours.setText("kW (Hours):");

        Max_Bat_Vol.setText("Maximum Battery Voltage:");

        Min_Av_Vol_Cell.setText("Minimum Average Volts per Cell:");

        Low_Cell.setText("Low Cell:");

        High_Cell.setText("High Cell:");

        mBatVol.setText("jLabel1");

        aVPower.setText("jLabel8");

        kWHours.setText("jLabel9");

        mXBatVol.setText("jLabel10");

        mAVCell.setText("jLabel11");

        lCell.setText("jLabel12");

        hCell.setText("jLabel13");

        jLabel14.setText("Activity Log:");

        aVLog.setColumns(20);
        aVLog.setRows(5);
        jScrollPane1.setViewportView(aVLog);

        Test_Completed.setText("Test Completed:");

        tComp.setText("jLabel16");

        Total_Test_Duration.setText("Total Test Duration:");

        tDuration.setText("jLabel18");

        jButton1.setText("Home");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Min_Av_Vol_Cell, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(185, 185, 185)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Min_Bat_Vol)
                                .addComponent(Average_Power))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Test_Completed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tComp)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(kW_Hours, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Max_Bat_Vol, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Low_Cell, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(High_Cell, javax.swing.GroupLayout.Alignment.TRAILING)))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(mBatVol)
                            .addComponent(aVPower)
                            .addComponent(kWHours)
                            .addComponent(mXBatVol)
                            .addComponent(mAVCell)
                            .addComponent(lCell)
                            .addComponent(hCell))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Total_Test_Duration)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tDuration)))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Test_Completed)
                    .addComponent(tComp)
                    .addComponent(Total_Test_Duration)
                    .addComponent(tDuration))
                .addGap(75, 75, 75)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Min_Bat_Vol)
                            .addComponent(mBatVol))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Average_Power)
                            .addComponent(aVPower))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kW_Hours)
                            .addComponent(kWHours))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Max_Bat_Vol)
                            .addComponent(mXBatVol))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Min_Av_Vol_Cell)
                            .addComponent(mAVCell))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Low_Cell)
                            .addComponent(lCell))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(High_Cell)
                            .addComponent(hCell)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EndScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EndScreen().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Average_Power;
    private javax.swing.JLabel High_Cell;
    private javax.swing.JLabel Low_Cell;
    private javax.swing.JLabel Max_Bat_Vol;
    private javax.swing.JLabel Min_Av_Vol_Cell;
    private javax.swing.JLabel Min_Bat_Vol;
    private javax.swing.JLabel Test_Completed;
    private javax.swing.JLabel Total_Test_Duration;
    private javax.swing.JTextArea aVLog;
    private javax.swing.JLabel aVPower;
    private javax.swing.JLabel hCell;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel kWHours;
    private javax.swing.JLabel kW_Hours;
    private javax.swing.JLabel lCell;
    private javax.swing.JLabel mAVCell;
    private javax.swing.JLabel mBatVol;
    private javax.swing.JLabel mXBatVol;
    private javax.swing.JLabel tComp;
    private javax.swing.JLabel tDuration;
    // End of variables declaration//GEN-END:variables
}
