/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Horne_Williams_PC1
 */
import java.awt.Color; 
import java.awt.Dimension;
import javax.swing.*;


public class GUI_Monitor extends javax.swing.JFrame {

    /**
     * Creates new form Monitor
     */
    public GUI_Monitor() {
        initComponents();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        C_V = new javax.swing.JTextArea();
        Battery_Voltage = new javax.swing.JLabel();
        Power_kW = new javax.swing.JLabel();
        AV_Cell = new javax.swing.JLabel();
        High_Cell = new javax.swing.JLabel();
        kW_Hours = new javax.swing.JLabel();
        Low_Cell = new javax.swing.JLabel();
        Battery_Amperage = new javax.swing.JLabel();
        Activity_Log = new javax.swing.JLabel();
        Duration = new javax.swing.JLabel();
        Test_Completed = new javax.swing.JLabel();
        Pause_Button = new javax.swing.JButton();
        Cell_Voltage = new javax.swing.JLabel();
        Abort = new javax.swing.JButton();
        bVol = new javax.swing.JLabel();
        pKW = new javax.swing.JLabel();
        kWHours = new javax.swing.JLabel();
        bAmp = new javax.swing.JLabel();
        aVPCell = new javax.swing.JLabel();
        lCell = new javax.swing.JLabel();
        hCell = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        tCompleted = new javax.swing.JLabel();
        dUration = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        C_V.setColumns(20);
        C_V.setRows(5);
        jScrollPane1.setViewportView(C_V);

        Battery_Voltage.setText("Battery Voltage:");

        Power_kW.setText("Power (kW):");

        AV_Cell.setText("Average Volts per Cell:");

        High_Cell.setText("High Cell:");

        kW_Hours.setText("kW Hours:");

        Low_Cell.setText("Low Cell:");

        Battery_Amperage.setText("Battery Amperage:");

        Activity_Log.setText("Activity Log:");

        Duration.setText("Duration:");

        Test_Completed.setText("Test Completed:");

        Pause_Button.setText("Pause");
        Pause_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pause_ButtonMouseClicked(evt);
            }
        });

        Cell_Voltage.setText("Cell Voltages:");

        Abort.setText("Abort");
        Abort.setVisible(false);
        Abort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbortActionPerformed(evt);
            }
        });

        bVol.setText("jLabel1");

        pKW.setText("jLabel2");

        kWHours.setText("jLabel3");

        bAmp.setText("jLabel4");

        aVPCell.setText("jLabel5");

        lCell.setText("jLabel6");

        hCell.setText("jLabel7");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        tCompleted.setText("jLabel8");

        dUration.setText("jLabel9");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        getContentPane().setBackground(Color.WHITE);
        
        getContentPane().setPreferredSize( new Dimension(800,480) );
        getContentPane().setMaximumSize( new Dimension(800,480) );
        getContentPane().setMinimumSize( new Dimension(800,480) );
        
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cell_Voltage)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Test_Completed)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tCompleted)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Duration)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dUration)
                        .addGap(193, 193, 193))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Power_kW)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(pKW))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(kW_Hours)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(kWHours))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(Battery_Voltage)
                                                .addGap(18, 18, 18)
                                                .addComponent(bVol)))
                                        .addGap(83, 83, 83)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(AV_Cell)
                                                    .addComponent(Low_Cell))
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(aVPCell)
                                                    .addComponent(lCell)))
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(High_Cell)
                                                .addGap(18, 18, 18)
                                                .addComponent(hCell))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Battery_Amperage)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(bAmp))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 420, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Activity_Log)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Pause_Button)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Abort))
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(108, 108, 108))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Duration)
                    .addComponent(Test_Completed)
                    .addComponent(tCompleted)
                    .addComponent(dUration))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Battery_Voltage)
                    .addComponent(AV_Cell)
                    .addComponent(bVol)
                    .addComponent(aVPCell))
                .addGap(4, 4, 4)
                .addComponent(Activity_Log)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Low_Cell)
                            .addComponent(Power_kW)
                            .addComponent(pKW)
                            .addComponent(lCell))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kW_Hours)
                            .addComponent(kWHours)
                            .addComponent(High_Cell)
                            .addComponent(hCell))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Battery_Amperage)
                            .addComponent(bAmp)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(Cell_Voltage)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pause_Button)
                            .addComponent(Abort))))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void Pause_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pause_ButtonMouseClicked
        // TODO add your handling code here:
        if ((pauseCount % 2) == 0){
        Pause_Button.setText("Resume");    
        getContentPane().setBackground(Color.RED);
        Abort.setVisible(true);
        
        pauseCount ++; 
       
        }
        
        else {
        Pause_Button.setText("Pause ");    
        getContentPane().setBackground(Color.WHITE);
        Abort.setVisible(false);
        
        pauseCount ++;
            
        }
        
        //System.out.println(pauseCount);
    }

    //GEN-LAST:event_Pause_ButtonMouseClicked

    private void AbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbortActionPerformed
        // TODO add your handling code here:
        
        int dialogButton = JOptionPane.YES_NO_OPTION;
        int dialogResult = (JOptionPane.showConfirmDialog(null,
        "Do you really want to Abort the Test?", "Abort", dialogButton));
        
        
        
        if (dialogResult == JOptionPane.YES_OPTION){
          
            GUIEndScreen end = new GUIEndScreen();
                
                end.setResizable(false);
		end.setVisible( true );
            
        }
    }//GEN-LAST:event_AbortActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AV_Cell;
    private javax.swing.JButton Abort;
    private javax.swing.JLabel Activity_Log;
    private javax.swing.JLabel Battery_Amperage;
    private javax.swing.JLabel Battery_Voltage;
    private javax.swing.JTextArea C_V;
    private javax.swing.JLabel Cell_Voltage;
    private javax.swing.JLabel Duration;
    private javax.swing.JLabel High_Cell;
    private javax.swing.JLabel Low_Cell;
    private javax.swing.JButton Pause_Button;
    private javax.swing.JLabel Power_kW;
    private javax.swing.JLabel Test_Completed;
    private javax.swing.JLabel aVPCell;
    private javax.swing.JLabel bAmp;
    private javax.swing.JLabel bVol;
    private javax.swing.JLabel dUration;
    private javax.swing.JLabel hCell;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel kWHours;
    private javax.swing.JLabel kW_Hours;
    private javax.swing.JLabel lCell;
    private javax.swing.JLabel pKW;
    private javax.swing.JLabel tCompleted;
    private int pauseCount;
    // End of variables declaration//GEN-END:variables
}


    


