/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

/**
 *
 * @author Horne_Williams_PC1
 */
import java.awt.Color; 
import java.awt.Dimension;
import javax.swing.*;


public class GUI_Monitor extends javax.swing.JFrame {

    /**
     * Creates new form Monitor
     */
    public GUI_Monitor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        
        
        jScrollPane1 = new javax.swing.JScrollPane();
        C_V = new javax.swing.JTextArea();
        Battery_Voltage = new javax.swing.JLabel();
        Power_kW = new javax.swing.JLabel();
        AV_Cell = new javax.swing.JLabel();
        High_Cell = new javax.swing.JLabel();
        B_Voltage = new javax.swing.JTextField();
        P_kW = new javax.swing.JTextField();
        kW_H = new javax.swing.JTextField();
        AV_p = new javax.swing.JTextField();
        L_C = new javax.swing.JTextField();
        H_C = new javax.swing.JTextField();
        kW_Hours = new javax.swing.JLabel();
        Low_Cell = new javax.swing.JLabel();
        Battery_Amperage = new javax.swing.JLabel();
        B_Amp = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        Ac_Log = new javax.swing.JTextArea();
        Activity_Log = new javax.swing.JLabel();
        Duration = new javax.swing.JLabel();
        Dur = new javax.swing.JTextField();
        Test_Completed = new javax.swing.JLabel();
        T_Com = new javax.swing.JTextField();
        Pause_Button = new javax.swing.JButton();
        Cell_Voltage = new javax.swing.JLabel();
        Abort = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        C_V.setColumns(20);
        C_V.setRows(5);
        jScrollPane1.setViewportView(C_V);

        Battery_Voltage.setText("Battery Voltage");

        Power_kW.setText("Power (kW)");

        AV_Cell.setText("Average Volts per Cell");

        High_Cell.setText("High Cell");

        B_Voltage.setText("jTextField1");

        P_kW.setText("jTextField2");

        kW_H.setText("jTextField3");

        AV_p.setText("jTextField4");

        L_C.setText("jTextField5");

        H_C.setText("jTextField6");

        kW_Hours.setText("kW Hours");

        Low_Cell.setText("Low Cell");

        Battery_Amperage.setText("Battery Amperage");

        B_Amp.setText("jTextField7");

        Ac_Log.setColumns(20);
        Ac_Log.setRows(5);
        jScrollPane2.setViewportView(Ac_Log);

        Activity_Log.setText("Activity Log");

        Duration.setText("Duration");

        Dur.setText("jTextField8");

        Test_Completed.setText("Test Completed");

        T_Com.setText("jTextField9");

        Pause_Button.setText("Pause");
        Pause_Button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Pause_ButtonMouseClicked(evt);
            }
        });

        Cell_Voltage.setText("Cell Voltages");

        Abort.setText("Abort");
        Abort.setVisible(false);
        Abort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AbortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        getContentPane().setBackground(Color.WHITE);
        
        getContentPane().setPreferredSize( new Dimension(800,480) );
        getContentPane().setMaximumSize( new Dimension(800,480) );
        getContentPane().setMinimumSize( new Dimension(800,480) );
        
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cell_Voltage)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Battery_Voltage)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(Power_kW)
                                            .addComponent(kW_Hours)
                                            .addComponent(Battery_Amperage))
                                        .addGap(65, 65, 65)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(B_Voltage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(kW_H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(P_kW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(72, 72, 72)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(Low_Cell)
                                                    .addComponent(High_Cell)
                                                    .addComponent(AV_Cell)))
                                            .addComponent(B_Amp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(L_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(AV_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(H_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Test_Completed)
                                .addGap(18, 18, 18)
                                .addComponent(T_Com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Activity_Log)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Duration)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Dur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Pause_Button)
                        .addGap(18, 18, 18)
                        .addComponent(Abort)
                        .addGap(44, 44, 44))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Duration)
                    .addComponent(Dur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Test_Completed)
                    .addComponent(T_Com, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Battery_Voltage)
                            .addComponent(B_Voltage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AV_Cell)
                            .addComponent(AV_p, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Activity_Log)
                        .addGap(5, 5, 5)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Power_kW)
                                .addComponent(P_kW, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Low_Cell, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(L_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(kW_Hours)
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Battery_Amperage)
                                    .addComponent(B_Amp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kW_H, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(H_C, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(High_Cell)))))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(Cell_Voltage)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Pause_Button)
                            .addComponent(Abort))))
                .addGap(70, 70, 70))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Pause_ButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Pause_ButtonMouseClicked
        // TODO add your handling code here:
        if ((pauseCount % 2) == 0){
        Pause_Button.setText("Resume");    
        getContentPane().setBackground(Color.RED);
        Abort.setVisible(true);
        
        pauseCount ++; 
       
        }
        
        else {
        Pause_Button.setText("Pause ");    
        getContentPane().setBackground(Color.WHITE);
        Abort.setVisible(false);
        
        pauseCount ++;
            
        }
        
        //System.out.println(pauseCount);
    }

    //GEN-LAST:event_Pause_ButtonMouseClicked

    private void AbortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AbortActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null,
        "Do you really want to Abort the Test?", "Abort", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_AbortActionPerformed

    /**
     * @param args the command line arguments
     */
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AV_Cell;
    private javax.swing.JTextField AV_p;
    private javax.swing.JButton Abort;
    private javax.swing.JTextArea Ac_Log;
    private javax.swing.JLabel Activity_Log;
    private javax.swing.JTextField B_Amp;
    private javax.swing.JTextField B_Voltage;
    private javax.swing.JLabel Battery_Amperage;
    private javax.swing.JLabel Battery_Voltage;
    private javax.swing.JTextArea C_V;
    private javax.swing.JLabel Cell_Voltage;
    private javax.swing.JTextField Dur;
    private javax.swing.JLabel Duration;
    private javax.swing.JTextField H_C;
    private javax.swing.JLabel High_Cell;
    private javax.swing.JTextField L_C;
    private javax.swing.JLabel Low_Cell;
    private javax.swing.JTextField P_kW;
    private javax.swing.JButton Pause_Button;
    private javax.swing.JLabel Power_kW;
    private javax.swing.JTextField T_Com;
    private javax.swing.JLabel Test_Completed;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kW_H;
    private javax.swing.JLabel kW_Hours;
    private int pauseCount;
    // End of variables declaration//GEN-END:variables
}


    


