package GUI;

/**
 *
 * @author srp5391, jmalafronte
 * Creates End screen Jframe
 */


import java.awt.*;
import javax.swing.*;


public class GUIEndScreen extends JFrame {

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public JLabel Average_Power;
    public JLabel High_Cell;
    public JLabel Low_Cell;
    public JLabel Max_Bat_Vol;
    public JLabel Min_Av_Vol_Cell;
    public JLabel Min_Bat_Vol;
    public JLabel Test_Completed;
    public JLabel Total_Test_Duration;
    public JTextArea aVLog;
    public JLabel aVPower;
    public JLabel hCell;
    public JButton homeButton;
    public JLabel jLabel14;
    public JScrollPane jScrollPane1;
    public JLabel kWHours;
    public JLabel kW_Hours;
    public JLabel lCell;
    public JLabel mAVCell;
    public JLabel mBatVol;
    public JLabel mXBatVol;
    public JLabel tComp;
    public JLabel tDuration;
    // End of variables declaration//GEN-END:variables
	
    /**
     * Creates new form EndScreen
     */
    public GUIEndScreen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Min_Bat_Vol = new JLabel();
        Average_Power = new JLabel();
        kW_Hours = new JLabel();
        Max_Bat_Vol = new JLabel();
        Min_Av_Vol_Cell = new JLabel();
        Low_Cell = new JLabel();
        High_Cell = new JLabel();
        mBatVol = new JLabel();
        aVPower = new JLabel();
        kWHours = new JLabel();
        mXBatVol = new JLabel();
        mAVCell = new JLabel();
        lCell = new JLabel();
        hCell = new JLabel();
        jLabel14 = new JLabel();
        jScrollPane1 = new JScrollPane();
        aVLog = new JTextArea();
        Test_Completed = new JLabel();
        tComp = new JLabel();
        Total_Test_Duration = new JLabel();
        tDuration = new JLabel();
        homeButton = new JButton();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setBackground(new Color(255, 255, 255));

        Min_Bat_Vol.setText("Minimum Battery Voltage:");
        Min_Bat_Vol.setToolTipText("");

        Average_Power.setText("Average Power:");

        kW_Hours.setText("kW (Hours):");

        Max_Bat_Vol.setText("Maximum Battery Voltage:");

        Min_Av_Vol_Cell.setText("Minimum Average Volts per Cell:");

        Low_Cell.setText("Low Cell:");

        High_Cell.setText("High Cell:");

        mBatVol.setText("jLabel1");

        aVPower.setText("jLabel8");

        kWHours.setText("jLabel9");

        mXBatVol.setText("jLabel10");

        mAVCell.setText("jLabel11");

        lCell.setText("jLabel12");

        hCell.setText("jLabel13");

        jLabel14.setText("Activity Log:");

        aVLog.setColumns(20);
        aVLog.setRows(5);
        jScrollPane1.setViewportView(aVLog);

        Test_Completed.setText("Test Completed:");

        tComp.setText("jLabel16");

        Total_Test_Duration.setText("Total Test Duration:");

        tDuration.setText("jLabel18");

        homeButton.setText("Home");

        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        getContentPane().setBackground(Color.WHITE);
        
        getContentPane().setPreferredSize( new Dimension(800,480) );
        getContentPane().setMaximumSize( new Dimension(800,480) );
        getContentPane().setMinimumSize( new Dimension(800,480) );
        
        
        layout.setHorizontalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(Min_Av_Vol_Cell, GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(185, 185, 185)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.TRAILING)
                                .addComponent(Min_Bat_Vol)
                                .addComponent(Average_Power))))
                    .addGroup(GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(Test_Completed)
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(tComp)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(kW_Hours, GroupLayout.Alignment.TRAILING)
                                .addComponent(Max_Bat_Vol, GroupLayout.Alignment.TRAILING)
                                .addComponent(Low_Cell, GroupLayout.Alignment.TRAILING)
                                .addComponent(High_Cell, GroupLayout.Alignment.TRAILING)))))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(homeButton)
                        .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(mBatVol)
                            .addComponent(aVPower)
                            .addComponent(kWHours)
                            .addComponent(mXBatVol)
                            .addComponent(mAVCell)
                            .addComponent(lCell)
                            .addComponent(hCell))
                        .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 180, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 204, GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Total_Test_Duration)
                                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tDuration)))
                        .addGap(28, 28, 28))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                    .addComponent(Test_Completed)
                    .addComponent(tComp)
                    .addComponent(Total_Test_Duration)
                    .addComponent(tDuration))
                .addGap(75, 75, 75)
                .addComponent(jLabel14)
                .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(Min_Bat_Vol)
                            .addComponent(mBatVol))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(Average_Power)
                            .addComponent(aVPower))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(kW_Hours)
                            .addComponent(kWHours))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(Max_Bat_Vol)
                            .addComponent(mXBatVol))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(Min_Av_Vol_Cell)
                            .addComponent(mAVCell))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(Low_Cell)
                            .addComponent(lCell))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(GroupLayout.Alignment.BASELINE)
                            .addComponent(High_Cell)
                            .addComponent(hCell)))
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 234, GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(homeButton)
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * reset gui components for new test
     */
    public void resetGUI()
    {
    	
    }
    
}